zed2 1
zed2 '"HELLO WORLD"'
zed2 'a=1+1; a'
zed2 'if false { 1 } else { 2 }'
zed2 'a=2; a > 1'
zed2 'true && false'
zed2 'a=1; while a < 5 { print a; a = a + 1 }'
zed2 'stdin;'
zed2 '/aaa/g'
zed2 '[1,2,3]'
zed2 '["AAA":1, "BBB":2]'
zed2 '"AAA".sub(/A/g, "B")'
valgrind zed2 '"AAA".sub_block(/A/g) { it.lower_case() }' 2> aaa
echo aaa | zed2 '.sub(/a/, "b").chomp()'
echo abc | zed2 '.scan_block(/./) { it.upper_case() }.join("+")'
echo abc | zed2 '.index("c", -1)'
echo abc | zed2 '.index_regex(/b/, -1)'
echo abcabc | zed2 '.rindex_regex(/b/, -1)'
echo ABCABCABC | zed2 '.chomp().sub_count(/B/g, "C", 2) == "ACCACCABC"'
echo A,B,C | zed2 'a=.split(/,/); a[0] == "A" && a[1] == "B" && a[2] == "C"'
echo abc | zed2 '.chomp().reverse()'
zed2 '"ABCDEFG".chomp().substring(0,1)'
zed2 '"ABCDEFG".length()'
zed2 '"ABCDEFG".compare("ZZZZ")'
zed2 '"ABCDEFG".index_regex(/B/, -1)'
zed2 '"ABCDEFG".replace(1, "Z")'
zed2 '"ABC,DEF,GHI".split_char(",")'
zed2 '"ABC".delete(0,2)'
zed2 '[1,2] + [3]'
zed2 '["1":1,"2":2] + ["3":3]'
zed2 '[1] == [2]'
zed2 '[1,2,3,4,5].filter { it > 2 }'
zed2 '[1,2,3,4,5].map { it + 1 }'
zed2 '["ZA", "ZB", "ZC"].each { print it; }'
zed2 '["AAA","BBB","CCC"].map { it.substring(0,1) }'
#valgrind --leak-check=full zed2 'l=["AAA", "BBB"]; l[1]="CCC"; l[0] == "AAA" && l[1] == "CCC"'
#valgrind --leak-check=full zed2 'l=["AAA":1, "BBB":2]; l["CCC"]=3; l["AAA"] == 1 && l["BBB"] == 2 && l["CCC"]==3'
#zed2 'm=["AAA":1, "BBB":2]; m["CCC"] = 3; m["AAA"] == 1 && m["BBB"] == 2 && m["CCC"] == 3'
